

name: CI


on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


  workflow_dispatch:


jobs:

  check_issues:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3


      - name: Install dependencies
        run: |
          sudo apt install jq
          pip install pylint
          pip install -r requirements.txt
          
      - name: Lint
        run: pylint -E main.py

      #- name: Test API
        #run: |
          #python main.py &
          
